resourcepack:
  enabled: true
  url: "https://github.com/TechnicFox/Emojify/raw/refs/heads/master/data/Emojify.zip" #url to the resource pack
  sha1: "45b27850908e374ae1fb7feadaa2777bd1216e6c" #sha1 hash of the resource pack
  prompt: "&6Please download the Emojify resource pack (without it plugin will not work)" #prompt when player joins the server
  force: false #force the resource pack
MainMenuConfig:
  #Can be used for custom menu.
  #七 - is a negative space symbol used to align the menu.
  #&f - is a color code (without it your custom menu will be dark).
  invName: "&f七七七七七七七七ㇺ"
  slots: 54 #Number of slots in the inventory. IT HAS TO BE A MULTIPLE OF 9.
inventories:
  slot0:
    name: "&b&lHearts"  #name of the item in the main inventory
    invName: "&f七七七七七七七七ㇺ"
    slots: 54
    id: 101 #id of the custom item

slot0:
  slot0:
    name: "媀" #custom character that can be changed into an emoji
    id: 101 #id of the custom item
  slot1:
    name: "鬣"
    id: 102
  slot2:
    name: "觮"
    id: 103
  slot3:
    name: "継"
    id: 104
  slot4:
    name: "佃"
    id: 105
  slot5:
    name: "青"
    id: 106
  slot6:
    name: "橙"
    id: 107
  slot7:
    name: "紫"
    id: 108
  slot8:
    name: "梾"
    id: 109
  slot9:
    name: "白"
    id: 110
  slot10:
    name: "黒"
    id: 111
